/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectotienda;

import java.util.Date;

/**
 *
 * @author soviedog
 */
public class Factura extends javax.swing.JFrame {


    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTransparente1 = new LIB.JPanelTransparente();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Cantidadarticulos = new javax.swing.JTextField();
        Iva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura Electronica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 153, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jPanelTransparente1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tienda Antigua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        jPanelTransparente1.setColorSecundario(new java.awt.Color(153, 153, 153));
        jPanelTransparente1.setLayout(null);

        jLabel1.setText("Nombre Cliente......");
        jPanelTransparente1.add(jLabel1);
        jLabel1.setBounds(10, 60, 120, 16);

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanelTransparente1.add(Nombre);
        Nombre.setBounds(200, 60, 110, 22);

        jLabel2.setText("Cedula Cliente.....");
        jPanelTransparente1.add(jLabel2);
        jLabel2.setBounds(10, 100, 100, 16);
        jPanelTransparente1.add(Cedula);
        Cedula.setBounds(200, 100, 110, 22);
        jPanelTransparente1.add(Correo);
        Correo.setBounds(200, 140, 110, 22);

        jLabel3.setText("Correo Cliente.....");
        jPanelTransparente1.add(jLabel3);
        jLabel3.setBounds(10, 140, 100, 16);

        jLabel4.setText("Monto Total Facturado.....");
        jPanelTransparente1.add(jLabel4);
        jLabel4.setBounds(20, 270, 140, 16);

        jLabel9.setText("IVA....");
        jPanelTransparente1.add(jLabel9);
        jLabel9.setBounds(40, 230, 80, 16);
        jPanelTransparente1.add(Total);
        Total.setBounds(200, 270, 110, 22);

        jLabel6.setText("Cantidad de articulos....");
        jPanelTransparente1.add(jLabel6);
        jLabel6.setBounds(10, 190, 150, 16);
        jPanelTransparente1.add(Cantidadarticulos);
        Cantidadarticulos.setBounds(200, 190, 110, 22);
        jPanelTransparente1.add(Iva);
        Iva.setBounds(200, 230, 110, 22);

        jLabel5.setText("Fecha de Compra....");
        jPanelTransparente1.add(jLabel5);
        jLabel5.setBounds(10, 30, 120, 16);
        jPanelTransparente1.add(Fecha);
        Fecha.setBounds(200, 20, 110, 22);

        jPanel1.add(jPanelTransparente1);
        jPanelTransparente1.setBounds(0, 20, 390, 320);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Cantidadarticulos;
    public static javax.swing.JTextField Cedula;
    public static javax.swing.JTextField Correo;
    public static javax.swing.JTextField Fecha;
    public static javax.swing.JTextField Iva;
    public static javax.swing.JTextField Nombre;
    public static javax.swing.JTextField Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelTransparente jPanelTransparente1;
    // End of variables declaration//GEN-END:variables
}
