/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectotienda;

import javax.swing.JOptionPane;

/**
 *
 * @author soviedog
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTransparente2 = new LIB.JPanelTransparente();
        jPanelTransparente3 = new LIB.JPanelTransparente();
        INGRESAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        USER = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        Pass = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jPanelTransparente3.setColorPrimario(new java.awt.Color(255, 153, 0));
        jPanelTransparente3.setLayout(null);

        INGRESAR.setText("Ingresar");
        INGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESARActionPerformed(evt);
            }
        });
        jPanelTransparente3.add(INGRESAR);
        INGRESAR.setBounds(40, 160, 90, 30);

        jButton2.setText("Salir");
        jPanelTransparente3.add(jButton2);
        jButton2.setBounds(150, 160, 60, 30);
        jPanelTransparente3.add(USER);
        USER.setBounds(100, 50, 100, 30);

        PASSWORD.setText("jPasswordField1");
        jPanelTransparente3.add(PASSWORD);
        PASSWORD.setBounds(100, 100, 100, 30);

        Pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/proyectotienda/Imagenes/icons8_password_26px.jpg"))); // NOI18N
        jPanelTransparente3.add(Pass);
        Pass.setBounds(60, 90, 50, 40);

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/proyectotienda/Imagenes/icons8_user_account_26px.jpg"))); // NOI18N
        jPanelTransparente3.add(User);
        User.setBounds(60, 40, 40, 40);

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel4.setText("Iniciar Sesión");
        jPanelTransparente3.add(jLabel4);
        jLabel4.setBounds(60, 10, 160, 20);

        getContentPane().add(jPanelTransparente3);
        jPanelTransparente3.setBounds(160, 50, 260, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/proyectotienda/Imagenes/adventure-fantasy-map-runescape-wallpaper-preview.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESARActionPerformed
        // TODO add your handling code here:
        String usuario="Steph";
        String contraseña="1234";
        String pass=new String(PASSWORD.getPassword());
        if(USER.getText().equals(usuario)&&pass.equals(contraseña)){
            Tienda ingreso=new Tienda();
            ingreso.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Password and user error");
        }
    }//GEN-LAST:event_INGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INGRESAR;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JLabel Pass;
    private javax.swing.JTextField USER;
    private javax.swing.JLabel User;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private LIB.JPanelTransparente jPanelTransparente2;
    private LIB.JPanelTransparente jPanelTransparente3;
    // End of variables declaration//GEN-END:variables
}
